version: "3"
services:
  perlcryptblowfish:
    command: /usr/bin/rpmbuild -ba perl-Crypt-Blowfish.spec
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
      dockerfile: Dockerfile.crypt-blowfish
  perlmd5:
    command: /usr/bin/rpmbuild -ba perl-MD5.spec
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
      dockerfile: Dockerfile.md5
  perlmcrypt:
    command: /usr/bin/rpmbuild -ba perl-Mcrypt.spec
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
      dockerfile: Dockerfile.mcrypt
  perluuid:
    command: /usr/bin/rpmbuild -ba perl-UUID.spec
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
      dockerfile: Dockerfile.uuid
  perlcryptx:
    command: /usr/bin/rpmbuild -ba perl-CryptX.spec
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
      dockerfile: Dockerfile.cryptx

volumes:
  rpm7:
    name: rpm7
