version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.9

workflows:
  perlmods:
    jobs:
      - docker-rpmbuild/rpmbuild:
          name: perlcryptblowfish
          base_service: centos7perlbase
          build_service: perlcryptblowfish
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: perlmd5
          base_service: centos7perlbase
          build_service: perlmd5
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: perlmcrypt
          base_service: centos7perlbase
          build_service: perlmcrypt
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: perluuid
          base_service: centos7perlbase
          build_service: perluuid
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: perlcryptx
          base_service: centos7perlbase
          build_service: perlcryptx
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos6perlcryptx
          base_service: centos6perlbase
          build_service: centos6perlcryptx
          bintray_uploader: centos6bintray
